---
# file: tasks/main.yml
# Top-level installer for mongodb_exporter.
#
# @see https://github.com/dcu/mongodb_exporter
#

# - name: set role variables, if necessary
#   include: set-role-variables.yml

- name: Create the Mongo Exporter group
  group:
    name: "{{ mongodb_exporter_group }}"
    state: present
    system: true

- name: Create the Mongo Exporter user
  user:
    name: "{{ mongodb_exporter_user }}"
    groups: "{{ mongodb_exporter_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    createhome: false
    home: /

- name: Download mongodb_exporter binary to local folder
  become: false
  get_url:
    url: "https://github.com/dcu/mongodb_exporter/releases/download/v{{ mongodb_exporter_version }}/mongodb_exporter-linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}"
    dest: "/tmp/mongodb_exporter-{{ mongodb_exporter_version }}-linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}"
  register: _download_binary
  until: _download_binary is succeeded
  retries: 5
  delay: 2
  delegate_to: localhost
  check_mode: false

# - name: Unpack mongodb_exporter binary
#   become: false
#   unarchive:
#     src: "/tmp/mongodb_exporter-{{ mongodb_exporter_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}.tar.gz"
#     dest: "/tmp"
#     creates: "/tmp/mongodb_exporter-{{ mongodb_exporter_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}/mongodb_exporter"
#   delegate_to: localhost
#   check_mode: false

- name: Propagate mongodb_exporter binaries
  copy:
    src: "/tmp/mongodb_exporter-{{ mongodb_exporter_version }}-linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}"
    dest: "/usr/local/bin/mongodb_exporter"
    mode: 0755
    owner: root
    group: root
  notify:
    - restart mongodb exporter
  when: not ansible_check_mode

- name: Copy the mongodb_exporter systemd service file
  template:
    src: mongodb_exporter.service.j2
    dest: /etc/systemd/system/mongodb_exporter.service
    owner: root
    group: root
    mode: 0644
  no_log: true
  notify:
    - restart mongodb exporter

- name: Ensure mongodb_exporter is enabled on boot
  systemd:
    name: mongodb_exporter
    enabled: true
